server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead-authuser
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true